### ISSUE TITLE
undefined method `|'

### ISSUE THREAD

**Issue by pbelouin** [XPBytes/administrate-field-hyperlink#3]
Hello, and thank you for this useful plugin! I seem to have an issue however: when I do have a link to display, I end up with the following error:

undefined method `|' for "https://wikidata.org/wiki/Q3158110":String

The code responsible for this seems to be:

`      def present?
        (data.presence | options.fetch(:fallback_href) { nil }).present?
      end`

and here is the trace:

administrate-field-hyperlink (0.3.0) lib/administrate/field/hyperlink.rb:13:in `present?'
administrate-field-hyperlink (0.3.0) app/views/fields/hyperlink/_show.html.erb:19:in `__usr_local_bundle_gems_administrate_field_hyperlink_______app_views_fields_hyperlink__show_html_erb__3349524331661453361_70328005211080'
actionview (5.1.5) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.5) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.5) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.5) lib/action_view/template.rb:155:in `render'
actionview (5.1.5) lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
actionview (5.1.5) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.5) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.5) lib/active_support/notifications/instrumenter.rb:21:in `instrument'

Any idea what I might be doing wrong? Thank you!

**Comment by SleeplessByte** [comment]
Woops! 

Thank you @pbelouin. This is a bug. I'll fix it and push a release.

**Comment by pbelouin** [comment]
awesome thanks for the quick reply!

**Comment by SleeplessByte** [comment]
Fixed in https://github.com/XPBytes/administrate-field-hyperlink/commit/6549ff83840816ca74387c2bbde726709c28c6d5. You can also see the missing test there.

Released as [:gem: 0.3.1](https://rubygems.org/gems/administrate-field-hyperlink/versions/0.3.1)
